name: Test

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu  # https://www.azul.com/downloads/?package=jdk
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip -r requirements-dev.txt
      - name: Run tests
        run: python tests/test_template.py
